In [12]:
import numpy as np

# Assignment

Q1. Create two arrays of six elements. Write the NumPy program to
count the number of instances of a value occurring in one array on
the condition of another array.

    Sample OutputOriginal arrays-
    [ 10 -10 10 -10 -10 10]
    [0.85 0.45 0.9 0.8 0.12 0.6 ]
    Number of instances of a value occurring in one array on the condition of another
    array: 3


0

Q2. Write the NumPy program to convert a Python dictionary to a
Numpy ndarray ?
    
    Original dictionary-
    {'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
    'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
    'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
    'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
    Type: <class 'dict'>
    ndarray-
    [[ 1. 0. 0. 2.]
    [ 3. 1. 0. -1.]
    [ 4. 1. 5. -1.]
    [ 3. -1. -1. -1.]]
    Type: <class 'numpy.ndarray'>


In [79]:
a={'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
#range(len(a))
#a['column0']['a']
#np.array(list(a.keys()))
keys,values=[],[]
for k1, v1 in a.items():
    for k2, v2 in v1.items():
        (keys.append(a[k1][k2]))
        
print((np.array(keys)).reshape(4,4))        

[[ 1.  0.  0.  2.]
 [ 3.  1.  0. -1.]
 [ 4.  1.  5. -1.]
 [ 3. -1. -1. -1.]]


Q3. Write the Numpy program to find and store the non-zero unique
rows in an array after comparing each row with other row in the
given matrix?
 
    Original array-
    [[ 1 1 0]
    [ 0 0 0]
    [ 0 2 3]
    [ 0 0 0]
    [ 0 -1 1]
    [ 0 0 0]]
    Non-zero unique rows-
    [[ 1 1 0]
    [ 0 2 3]
    [ 0 -1 1]]

In [71]:
a=np.array([[ 1, 1 ,0],[ 0 ,0, 0],[ 0, 2, 3],[ 0 ,0, 0],[0,-1, 1],[ 0 ,0, 0]])
zeros=np.array([0,0,0])
for i in a:
    if i in zeros:
        
    else:
        print(i)
        
        
        
        
    
        

        
        
    

Q4. Write the NumPy program to multiply the matrix by another matrix
of complex numbers and create a new matrix of complex
numbers?

    Sample outputFirst array-
    [ 1.+2.j 3.+4.j]
    Second array-
    [ 5.+6.j 7.+8.j]
    Product of above two arrays-
    (70-8j)

In [22]:
a=np.array((1+2.0j,3+4.0j),dtype=complex)
print(a)
b=np.array([ 5.+6.j ,7.+8.j])
print(b)
c=a.real*b.real
d=a.imag*b.imag
print(a.real*b.real)
print(a.imag*b.imag)
print(c*d)

[1.+2.j 3.+4.j]
[5.+6.j 7.+8.j]
[ 5. 21.]
[12. 32.]
[ 60. 672.]


Q5. Write a NumPy program to generate the matrix product of two
Arrays?

    Sample OutputMatrices and vectors.
    x-
    [[1, 0], [1, 1]]
    y-
    [[3, 1], [2, 2]]
    Matrix product of above two arrays-
    [[3 1]
    [5 3]]


In [24]:
x=np.array([[1, 0], [1, 1]])
print(x)
print(y)
y=np.array([[3, 1], [2, 2]])
print("Matrix product of above two arrays-\n",np.multiply(x,y))

[[1 0]
 [1 1]]
[[3 1]
 [2 2]]
Matrix product of above two arrays-
 [[3 0]
 [2 2]]


Q6. Write the NumPy program to find roots of the following
Polynomials?

    a) (x
    2
    - 4x + 7)
    b) x4
    - 11x3 + 9x2 + 11x ? 10
    Sample outputRoots of the first polynomial-
    [ 1. 1.]
    Roots of the second polynomial-
    [ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j
    0.91326132-0.4531004j ]

Q7. Write the NumPy program to calculate inverse of sine, cosine,
and inverse tangent for all elements in a given array?

    Sample outputInverse sine- [-1.57079633 0. 1.57079633]
    Inverse cosine- [3.14159265 1.57079633 0. ]
    Inverse tangent- [-0.78539816 0. 0.78539816]

In [61]:
a=np.array([-1,0,1])
print("inverse sine\n",np.arcsin(a))
print('Inverse cosine\n',np.arccos(a))
print('inverse tangent\n',np.arctan(a))

inverse sine
 [-1.57079633  0.          1.57079633]
Inverse cosine
 [3.14159265 1.57079633 0.        ]
inverse tangent
 [-0.78539816  0.          0.78539816]


Q8. Write the NumPy program to calculate the difference between in
neighbouring elements, element-wise of a given array?

    Sample outputOriginal array-
    [1 3 5 7 0]
    Difference between neighbouring elements, element-wise of the said array-
    [ 2 2 2 -7]

In [8]:
a=np.array([1, 3, 5, 7 ,0])
b=[a[i+1]-a[i] for i in range(0,len(a)-1)]
print("Difference between neighbouring elements, element-wise of the said array-\n",b)

Difference between neighbouring elements, element-wise of the said array-
 [2, 2, 2, -7]


Q9. Write the Python program to find the maximum and the minimum
value of a given flattened array?

    Expected OutputOriginal flattened array-
    [[0 1]
    [2 3]]
    Maximum value of the above flattened array3
    Minimum value of the above flattened array0

In [13]:
a=np.array([[0 ,1],[2, 3]])
#np.flat(a)
print("Maximum value of the above flattened array-",np.max(a))
print("Minimum value of the above flattened array-",np.min(a))

Maximum value of the above flattened array- 3
Minimum value of the above flattened array- 0


Q10. Write the NumPy program to calculate the difference between in
the maximum and the minimum values of a given array along the
second axis ?

    Expected OutputOriginal array-
    [[ 0 1 2 3 4 5]
    [ 6 7 8 9 10 11]]
    Difference between the maximum and the minimum values of the said array-
    [5 5]


In [14]:
a=np.array([[ 0 ,1 ,2, 3, 4, 5],[ 6, 7 ,8 ,9, 10 ,11]])
b=np.subtract(np.max(a),np.min(a))
b

11

Q11. Write the NumPy program to compute the weighted of the given
array ?

    Sample OutputOriginal array-
    [0 1 2 3 4]
    Weighted average of the said array2.6666666666666665

In [60]:
a=np.array([0, 1, 2 ,3, 4])
print("Weighted average of the said array-\n",np.average(a,weights=a))
#np.weighted_average()

Weighted average of the said array-
 3.0


Q12. Write the NumPy program to compute the mean, standard
deviation, and the variance of a given array along the second
axis?

    Sample outputOriginal array-
    [0 1 2 3 4 5]
    Mean- 2.5
    std- 1
    variance- 2.9166666666666665

In [41]:
a=np.array([0, 1, 2, 3, 4 ,5])
a
print("Mean-",np.mean(a))
print("Std-",np.std(a,axis=0))
print("Varience-",np.var(a))


Mean- 2.5
Std- 1.707825127659933
Varience- 2.9166666666666665


Q13. Write the Numpy program to compute the covariance matrix of the
two given arrays?
    
    Sample OutputOriginal array1-
    [0 1 2]
    Original array1-
    [2 1 0]
    Covariance matrix of the said arrays-
    [[ 1. -1.]
    [-1. 1.]]

In [49]:
a=np.array([0, 1, 2])
b=np.array([2,1,0])
print(a)
print(b)
print("Covariance matrix of the said arrays-\n",np.cov(a,b))

[0 1 2]
[2 1 0]
Covariance matrix of the said arrays-
 [[ 1. -1.]
 [-1.  1.]]


In [47]:
list(dir(np))

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distribu

In [53]:
np.histogram(np.array(np.random.randint(1,100,100)),bins=50)


(array([1, 3, 2, 1, 0, 2, 1, 1, 2, 1, 0, 3, 2, 2, 2, 0, 2, 4, 1, 1, 1, 3,
        4, 1, 1, 4, 1, 3, 4, 1, 1, 2, 0, 1, 2, 5, 4, 0, 2, 3, 5, 2, 3, 2,
        6, 1, 1, 3, 0, 3], dtype=int64),
 array([ 1.  ,  2.96,  4.92,  6.88,  8.84, 10.8 , 12.76, 14.72, 16.68,
        18.64, 20.6 , 22.56, 24.52, 26.48, 28.44, 30.4 , 32.36, 34.32,
        36.28, 38.24, 40.2 , 42.16, 44.12, 46.08, 48.04, 50.  , 51.96,
        53.92, 55.88, 57.84, 59.8 , 61.76, 63.72, 65.68, 67.64, 69.6 ,
        71.56, 73.52, 75.48, 77.44, 79.4 , 81.36, 83.32, 85.28, 87.24,
        89.2 , 91.16, 93.12, 95.08, 97.04, 99.  ]))

Q14. Write a NumPy program to compute the cross-correlation of two
given arrays ?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Cross-correlation of the said arrays-
    [ [ 2.33333333 2.16666667 ]
     [ 2.16666667 2.33333333 ] ]

In [63]:
a=np.array([0, 1, 3])
b=np.array([2 ,4, 5])

print("Cross-correlation of the said arrays-\n",np.cov(a,b))

Cross-correlation of the said arrays-
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


Q15. Write the NumPy program to compute Pearson product-moment
correlation coefficients of two given arrays?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Pearson product-moment correlation coefficients of the said arrays-
    [[1. 0.92857143]
    [0.92857143 1. ]]

In [64]:
a=np.array([0,1,3])
b=np.array([2,4,5])
print("product coreelation coefficient\n",np.corrcoef(a, b))

product coreelation coefficient
 [[1.         0.92857143]
 [0.92857143 1.        ]]


Q16. Write the python program to count the number of occurrences of
each value in a given array of non-negative integers?
 
Note: bincount() Function- It count the occurrence of each value in an array of the
non- negative integers in the range of the array between the minimum and maximum values
including the values that did not occur.

    Sample OutputOriginal array-
    [0, 1, 6, 1, 4, 1, 2, 2, 7]
    Number of occurrences of each value in array-
    [1 3 2 0 1 0 1 1]

In [67]:
a=np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
a
print(np.bincount(a))

[1 3 2 0 1 0 1 1]


Q17. Write a Numpy program to compute the histogram of nums
against the bins?

    Sample Outputnums- [0.5 0.7 1. 1.2 1.3 2.1]
    P a g e 29 | 44
    bins- [0 1 2 3]
    Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [58]:
nums=np.array([0.5, 0.7, 1., 1.2, 1.3, 2.1])
print("Result-\n",np.histogram(nums,bins=[0,1,2,3]))

Result-
 (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))


## Great Job!