# Assignment

In [2]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [3]:
a=np.ones((5,5),dtype=int)*6
print(a)
a[1:4,1:4]=0
print(a)


[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


In [4]:
# if you want to take no of rows and colums as an input from user
rows=int(input("Enter no of rows:"))
column=int(input("Enter no of column:"))
a=np.ones((rows,column),dtype=int)*6
a[1:rows-1,1:column-1]=0
print(a)

Enter no of rows:5
Enter no of column:4
[[6 6 6 6]
 [6 0 0 6]
 [6 0 0 6]
 [6 0 0 6]
 [6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [5]:
a=np.ones((8,8),dtype=int)
a[::2]=3
#a[:,1::2]=9
a[1::2]=9
#a[:,::2]=9
a[:,1::2]=9
a[1::2,1::2]=3
print(a)

[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [6]:
a=np.array([0, 12, 45.21 ,34, 99.91])
a=np.sort(a,kind='mergesort')
print("Sorted values in fahrenheit degrees-\n",a)
celcius=(5/9)*(a-32)
print("Values in Centigrade degress-\n",celcius)

Sorted values in fahrenheit degrees-
 [ 0.   12.   34.   45.21 99.91]
Values in Centigrade degress-
 [-17.77777778 -11.11111111   1.11111111   7.33888889  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [7]:
a=np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print("Real part of the  array-\n",a.real)
print("Imaginary part of the array-\n",a.imag)

Real part of the  array-
 [1.         0.70710678]
Imaginary part of the array-
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [8]:
Array1=np.array([ 0 ,10, 20, 40, 60])
#for i in Array1:
 #   print(i)
Array2=np.array([0,40])    
Array2  is Array1
l=[]
for i in Array1:
    if i in Array2:
        l.append(True)
        
        
    else:
        l.append(False)
        
print("Array after comparing each elements of array1 and array2\n",np.array(l))  
    

Array after comparing each elements of array1 and array2
 [ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [9]:
Array1=np.array([ 0 ,10, 20, 40, 60])
Array2=np.array([10, 30, 40]) 
l=[]
for i in Array1:
    if i in Array2:
        l.append(i)
print("Comman Values between two arrays-\n", np.array(l) )       
        

Comman Values between two arrays-
 [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [10]:
a=np.array([10, 10, 20 ,20 ,30 ,30])
l=[]
for i in a:
    if i  not in l:
        l.append(i)
print("Unique Element of the array-\n",np.array(l))        
a=  np.array([[1, 1], [2 ,3]])  
l=[]
for i in range(0,len(a)):
    for j in range(0,len(a)):
        if a[i,j] not in l:
            l.append(a[i,j])
            
        #print(a[i,j],end=" ")
    print()        
#print(l)          
        
print("Unique Element of the array-\n",np.array(l))   
    

Unique Element of the array-
 [10 20 30]


Unique Element of the array-
 [1 2 3]


In [11]:
a=np.random.randint(1,100,25).reshape(5,5)
print(a)
print(len(a))
l=[]
for i in range(0,len(a)):
    for j in range(0,len(a)):
        if a[i,j] not in l:
            l.append(a[i,j])
            
        #print(a[i,j],end=" ")
    print()        
print(l)          
        
        
    

[[11 41 39 22 27]
 [42 51 14 74 32]
 [ 2 29 79 33  2]
 [34 37  4 84 11]
 [76 11  5 25 18]]
5





[11, 41, 39, 22, 27, 42, 51, 14, 74, 32, 2, 29, 79, 33, 34, 37, 4, 84, 76, 5, 25, 18]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [12]:
Array1= np.array([ 0 ,10, 20 ,40, 60 ,80])
Array2= np.array([10, 30, 40, 50, 70])
#l=[i for i in Array1 if i not in Array2 and Array1]
l=[]
for i in Array1:
    if i not in Array2:
        l.append(i)
        l.sort()
for j in Array2:
    if j not in Array1:
        l.append(j) 
        l.sort()
                
            
            
       
print("Unique values that are in only one (not both) of the input arrays-\n",l)                
         
        


 

Unique values that are in only one (not both) of the input arrays-
 [0, 20, 30, 50, 60, 70, 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [13]:
arr=np.array(np.random.randint(1,100,35).reshape(5,-1))
print(arr)
l=[]
for i in range(0,len(arr)):
    for j in range(0,len(arr[i])):
        if arr[i,j] in arr:
            l.append(True)
        else:
            l.append(False)
print(l)            
            


[[96 14 29 13 83 42 84]
 [ 2 40 73 81 47 70 90]
 [60 96 76 50 93 82  4]
 [42 51 49 21 58 95 65]
 [62 15  5  9 74 61 42]]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [14]:
a=[1, 2, 3, 4]
b=a*2
print("Repeating 2 times\n",b)
c=a*3
print("Repeating 3 times\n",c)

Repeating 2 times
 [1, 2, 3, 4, 1, 2, 3, 4]
Repeating 3 times
 [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [15]:
a=np.array([1, 2, 3 ,4, 5, 6])
print("Maximum values-",a.argmax())
print("Minimum Values-",a.argmin())
# Function for the same purpose
def Max_Min_Index(arr):
    max_value_index=arr.argmax()
    min_value_index=arr.argmin()
    return max_value_index,min_value_index

x,y=Max_Min_Index(a)
print("Maximum values-",x)
print("Minimum values-",y)

Maximum values- 5
Minimum Values- 0
Maximum values- 5
Minimum values- 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [16]:
a=np.array([1,2])
b=np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [30]:
# Dear sir i'm seeing little bit wrong sample out here in sample array there is no 6 element in array but in 
# output its showing 6 elment as output as well,i think its little bit wrong input arra have benn taken as input
arr=np.array([[2,5],[4,4]])
print(arr)
print("Sort along the first axis:\n",np.sort(arr,axis=0))
print("Sort along the last axis:\n",np.sort(arr,axis=-1))# here we can use axis =1 as well it will be the same 

[[2 5]
 [4 4]]
Sort along the first axis:
 [[2 4]
 [4 5]]
Sort along the last axis:
 [[2 5]
 [4 4]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [24]:
first_names = ( 'Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery' )
last_names = ( 'Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum' )
sorted_name_index=np.lexsort((last_names,first_names))
print(sorted_name_index)

[0 3 2 4 1]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [41]:
a=np.array([[ 0, 10, 20],[20, 30 ,40]])
a
print("Values bigger than 10=",a[a>10])
print("There indices are:",np.where(a>10))
np.where()

Values bigger than 10= [20 20 30 40]
There indices are: (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [35]:
a=np.random.randn(4,4)
a
print("memory  size=",a.nbytes,"bytes")

memory  size= 128 bytes


## Great Job!